### ISSUE TITLE
Collapsible button icons aren't visible when browsers are overriding background colour

### ISSUE THREAD

**Issue by lewisnyman** [alphagov/tech-docs-template#161]
Firefox allows users to specify colour style overrides, one side effect of this is that icons tends to disappear. I'm guessing that's because they've been set using CSS background-image. [More on overriding colour styles information here.](https://accessibility.blog.gov.uk/2016/05/26/accessibility-and-me-marian-foley/)

![Firefox with the background colour overridden](https://user-images.githubusercontent.com/632390/42685788-e49a6d3a-868b-11e8-8162-ef210a1713e0.jpg)

I'm not sure how to fix this yet, but I heard that @nickcolley has been fix these issues in the design system, he might have some advice.

**Comment by nickcolley** [comment]
I'm drafting a blog post for some of the techniques we're using: https://docs.google.com/document/d/1YWgszOPxDY-OdMHc43A9GKmucQUM-299EBBw4X-mrgo/edit?usp=sharing

You could consider:

1. Inline SVG with `fill=currentColor`
2. CSS Triangles

```css
.collapsible__toggle-icon {
    position: absolute;
    top: 0;
    right: 0;
    left: 0;
    bottom: 0;
    margin: auto;
}

.collapsible__toggle-icon::after {
    display: block;
    content: '';
    position: absolute;
    top: 0;
    bottom: 0;
    right: 0;
    left: 0;
    margin: auto;
    width: 10px;
    height: 10px;
    transform: rotate(45deg);
    border: solid;
    border-width: 0 2px 2px 0;
}

.collapsible.is-open .collapsible__toggle-icon::after {
    transform: rotate(-135deg);
}
```
