### ISSUE TITLE
[Docs] Deploy via GitHub Workflow

### ISSUE THREAD

**Issue by alex-hedley** [alphagov/tech-docs-template#232]
I've created a simple [GitHub Pages](https://pages.github.com/) [Workflow](https://docs.github.com/en/actions/using-workflows) to deploy this template.

Update the `config.rb` (See [Middleman Github Pages - Project Page Path Issues](https://github.com/edgecase/middleman-gh-pages#project-page-path-issues))

```ruby
activate :relative_assets
set :relative_links, true
```

Create a `deploy.yml` file in the `.github/workflows/` folder.
```yml
name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "source/**"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write

jobs:
  build_and_deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up 💎 Ruby 3.2.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0
#           bundler-cache: true
        
      - name: Install Dependencies
        run: |
          echo 'Installing bundles...'
          gem install bundler
          bundle install
          bundle list | grep "middleman ("
        
      - name: Build
        run: bundle exec middleman build
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
```

Would it be worth adding this to the [Documentation Site](https://tdt-documentation.london.cloudapps.digital/publish_project/deploy/#github-pages)?
